security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt

    providers:
        main:
            memory:
                users:
                    admin:
                        password: '$2y$13$4svJGPjaSwA.hJr0f3ksEOYtCV8U5LzLGp08vJ.sV3uvPF2EgPW5.' # password
                        roles: [ 'ROLE_ADMIN' , 'ROLE_USER' ]

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            http_basic:
                realm: Secured Area
            anonymous: ~

    access_control:
        - { path: ^/admin , roles: ROLE_ADMIN }
