admin_index:
    path: /admin
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        route: all

index:
    path: /
    controller: 'App\Controller\AdminArticleController::articles'