#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

index:
  path: /
  controller: App\Controller\BlogController::entriesAction

login:
  path: /login
  controller: App\Controller\SecurityController::login

register:
  path: /registration
  controller: App\Controller\RegistrationController::register